<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="martin.20210515201503.2"><vh>@file ./j_to_z.py</vh></v>
<v t="martin.20210515201512.2"><vh>@auto ./README.md</vh></v>
</vnodes>
<tnodes>
</tnodes>
</leo_file>
